apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1
  version: "1.29"

managedNodeGroups:
  - name: my-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
