apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    app: frontend-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
