replicaCount: 1

image:
  repository: docker.io/REPLACE_ME/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
