name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub with Access Token
        # DOCKERHUB_TOKEN should be a Docker Hub access token, not your password
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./nodejs-app
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy to Kubernetes with Helm
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
          helm upgrade --install nodejs-app ./helm/nodejs-app \
            --set image.repository=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app \
            --set image.tag=latest \
            --namespace default --create-namespace
          helm upgrade --install frontend-app ./helm/frontend-app \
            --set image.repository=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend \
            --set image.tag=latest \
            --namespace default --create-namespace
